---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vm-grafana-oidc-secret
spec:
  type: kv-v1
  mount: /identity
  path: oidc/client/grafana-backup
  destination:
    name: vm-grafana-oidc-secret
    create: true
    transformation:
      includes:
        - client_id
        - client_secret
  vaultAuthRef: grafana
