---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cookie-secret
spec:
  type: kv-v2
  mount: kvv2
  path: core/oauth2-proxy/cookie-secret
  destination:
    name: cookie-secret
    create: true
  vaultAuthRef: oauth2-proxy
