---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth2-proxy
spec:
  type: kv-v1
  mount: /identity
  path: oidc/client/oauth2-proxy
  destination:
    name: oauth2-proxy
    create: true
    transformation:
      includes:
        - client_id
        - client_secret
  vaultAuthRef: oauth2-proxy
