---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: netbootxyz-ingress-basic-auth
spec:
  type: kv-v2
  mount: kvv2
  path: netbootxyz/ingress-basic-auth
  destination:
    name: netbootxyz-ingress-basic-auth
    create: true
  vaultAuthRef: netbootxyz
