---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: netbootxyz
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: netbootxyz
    serviceAccount: netbootxyz
