---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-servicemonitor
  labels:
    name: longhorn-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
    - port: manager
