---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: home-assistant
spec:
  endpoints:
    - interval: 1m
      params:
        format:
          - prometheus
      path: /api/prometheus
      port: http
      scheme: http
      bearerTokenSecret:
        key: token
        name: home-assistant-prometheus
        optional: false
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - home-assistant
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
