---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.email | required ".Values.email' is required"}}
    privateKeySecretRef:
      name: letsencrypt-dns-prod
    solvers:
      - dns01:
          route53:
            region: {{.Values.region | required ".Values.region' is required"}}
            accessKeyIDSecretRef:
              name: letsencrypt-dns-prod-credentials-secret
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: letsencrypt-dns-prod-credentials-secret
              key: AWS_SECRET_ACCESS_KEY
