---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: letsencrypt-dns-prod-credentials-secret
spec:
  type: kv-v2
  mount: kvv2
  path: cert-manager/letsencrypt-dns-prod-credentials-secret
  destination:
    name: letsencrypt-dns-prod-credentials-secret
    create: true
  vaultAuthRef: cert-manager
