---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: alertmanager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: victoria-metrics-stack-alertmanager
    serviceAccount: vmalertmanager-vm-victoria-metrics-k8s-stack
