---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: victoria-metrics-stack-grafana
    serviceAccount: vm-grafana
