---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: prometheus
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: victoria-metrics-stack-prometheus
    serviceAccount: vmsingle-vm-victoria-metrics-k8s-stack
