---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: credentials-homelab
spec:
  type: kv-v2
  mount: kvv2
  path: core/argocd/credentials/homelab
  destination:
    name: credentials-homelab
    labels:
      argocd.argoproj.io/secret-type: repository
    create: true
  vaultAuthRef: argocd
