---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc
spec:
  type: kv-v1
  mount: /identity
  path: oidc/client/argocd
  destination:
    name: oidc
    create: true
    labels:
      app.kubernetes.io/part-of: argocd
    transformation:
      includes:
        - client_id
        - client_secret
  vaultAuthRef: argocd
