---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-cli
spec:
  type: kv-v1
  mount: /identity
  path: oidc/client/argocd-cli
  destination:
    name: oidc-cli
    create: true
    labels:
      app.kubernetes.io/part-of: argocd
    transformation:
      includes:
        - client_id
  vaultAuthRef: argocd
