---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-dezeroku-user-secret
spec:
  type: kv-v2
  mount: kvv2
  path: services/minio/private/dezeroku-credentials
  destination:
    name: minio-dezeroku-user-secret
    create: true
  vaultAuthRef: minio
