---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-dezeroku-user-secret
spec:
  type: kv-v2
  mount: kvv2
  path: services/minio/private/dezeroku-credentials
  destination:
    name: minio-dezeroku-user-secret
    create: true
    transformation:
      excludes:
        - .*
      templates:
        CONSOLE_ACCESS_KEY:
          text: |
            {{`
            {{ .Secrets.username }}
            `}}
        CONSOLE_SECRET_KEY:
          text: |
            {{`
            {{ .Secrets.password }}
            `}}
  vaultAuthRef: minio
