---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nixys
    url: https://registry.nixys.ru/chartrepo/public
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: vault-secrets-operator
    namespace: vault-secrets-operator
    chart: hashicorp/vault-secrets-operator
    version: 0.2.0
    values:
      - values/vault-secrets-operator.yaml.gotmpl

  - name: longhorn-enhancements
    namespace: longhorn
    chart: ./charts/longhorn-enhancements
    version: 0.1.0

  - name: longhorn
    namespace: longhorn
    chart: longhorn/longhorn
    version: 1.5.3
    values:
      - values/longhorn.yaml.gotmpl

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    values:
      - values/ingress-nginx.yaml

  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.25.0
    values:
      - values/vault.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.3
    values:
      - values/cert-manager.yaml.gotmpl

  - name: cert-manager-cluster-issuer
    namespace: cert-manager
    chart: ./charts/cert-manager-cluster-issuer
    version: 0.1.0
    values:
      - values/cert-manager-cluster-issuer.yaml

  - name: kube-prometheus-stack-enhancements
    namespace: kube-prometheus-stack
    chart: ./charts/kube-prometheus-stack-enhancements
    version: 0.1.0

  - name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 55.11.0
    dependencies:
      - chart: nixys/universal-chart
        version: 2.4.0
        alias: grafana_dashboards
    values:
      - values/kube-prometheus-stack.yaml.gotmpl
      - values/grafana-dashboards.yaml.gotmpl

  - name: pgo
    namespace: pgo
    chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
    version: 5.5.0
    values:
      - values/pgo.yaml.gotmpl
