---
bases:
  - ../lib/base.yaml

repositories:
  - name: victoria-metrics
    url: https://victoriametrics.github.io/helm-charts/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nixys
    url: https://registry.nixys.ru/chartrepo/public
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: longhorn
    url: https://charts.longhorn.io
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler/
  - name: deliveryhero
    url: https://charts.deliveryhero.io/
  - name: minio
    url: https://operator.min.io/
  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests
  - name: argo-helm
    url: https://argoproj.github.io/argo-helm

releases:
  - name: vault-secrets-operator
    chart: hashicorp/vault-secrets-operator
    version: 0.5.1
    inherit:
      - template: default
  - name: vault-secrets-operator
    inherit:
      - template: argocd-app

  - name: longhorn
    chart: longhorn/longhorn
    version: 1.5.3
    inherit:
      - template: default
    dependencies:
      - chart: ./charts/longhorn-enhancements
        version: 0.1.0
  - name: longhorn
    inherit:
      - template: argocd-app

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    inherit:
      - template: default
  - name: ingress-nginx
    inherit:
      - template: argocd-app

  - name: vault
    chart: hashicorp/vault
    version: 0.27.0
    inherit:
      - template: default
  - name: vault
    inherit:
      - template: argocd-app

  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.14.4
    inherit:
      - template: default
    dependencies:
      - chart: ./charts/cert-manager-cluster-issuer
        version: 0.1.0
  - name: cert-manager
    inherit:
      - template: argocd-app

  - name: victoria-metrics-stack
    chart: victoria-metrics/victoria-metrics-k8s-stack
    version: 0.19.2
    values:
      - values/grafana-dashboards.yaml.gotmpl
    inherit:
      - template: default
    dependencies:
      - chart: nixys/universal-chart
        version: 2.4.0
        alias: grafana_dashboards
      - chart: ./charts/victoria-metrics-stack-enhancements
        version: 0.1.0
  - name: victoria-metrics-stack
    inherit:
      - template: argocd-app

  # A separate stack with longer retention period
  # for IoT related data
  # We only care about vmsingle here
  - name: vm-hass
    namespace: victoria-metrics-stack
    chart: victoria-metrics/victoria-metrics-k8s-stack
    version: 0.19.2
    inherit:
      - template: default
  - name: vm-hass
    values:
      - targetNamespace: victoria-metrics-stack
    inherit:
      - template: argocd-app

  - name: pgo
    chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
    version: 5.5.0
    inherit:
      - template: default
  - name: pgo
    inherit:
      - template: argocd-app

  - name: descheduler
    namespace: kube-system
    chart: descheduler/descheduler
    version: 0.29.0
    inherit:
      - template: default
  - name: descheduler
    values:
      - targetNamespace: kube-system
    inherit:
      - template: argocd-app

  - name: node-problem-detector
    namespace: kube-system
    chart: deliveryhero/node-problem-detector
    version: 2.3.12
    inherit:
      - template: default
  - name: node-problem-detector
    values:
      - targetNamespace: kube-system
    inherit:
      - template: argocd-app

  - name: minio-operator
    chart: minio/operator
    version: 5.0.11
    inherit:
      - template: default
  - name: minio-operator
    inherit:
      - template: argocd-app

  - name: oauth2-proxy
    chart: oauth2-proxy/oauth2-proxy
    version: 7.1.0
    inherit:
      - template: default
    dependencies:
      - chart: ./charts/oauth2-proxy-enhancements
        version: 0.1.0
  - name: oauth2-proxy
    inherit:
      - template: argocd-app

  - name: argocd
    chart: argo-helm/argo-cd
    version: 7.3.11
    inherit:
      - template: default
    dependencies:
      - chart: ./charts/argocd-enhancements
        version: 0.1.0
  - name: argocd-app
    values:
      - targetNamespace: argocd
      - targetName: argocd
    inherit:
      - template: argocd-app
