---
repositories:
  - name: victoria-metrics
    url: https://victoriametrics.github.io/helm-charts/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: nixys
    url: https://registry.nixys.ru/chartrepo/public
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: longhorn
    url: https://charts.longhorn.io
  - name: descheduler
    url: https://kubernetes-sigs.github.io/descheduler/
  - name: deliveryhero
    url: https://charts.deliveryhero.io/
  - name: minio
    url: https://operator.min.io/

releases:
  - name: vault-secrets-operator
    namespace: vault-secrets-operator
    chart: hashicorp/vault-secrets-operator
    version: 0.2.0
    values:
      - values/vault-secrets-operator.yaml.gotmpl

  - name: longhorn
    namespace: longhorn
    chart: longhorn/longhorn
    version: 1.5.3
    values:
      - values/longhorn.yaml.gotmpl

  - name: longhorn-enhancements
    namespace: longhorn
    chart: ./charts/longhorn-enhancements
    version: 0.1.0

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1
    values:
      - values/ingress-nginx.yaml

  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.25.0
    values:
      - values/vault.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.3
    values:
      - values/cert-manager.yaml.gotmpl

  - name: cert-manager-cluster-issuer
    namespace: cert-manager
    chart: ./charts/cert-manager-cluster-issuer
    version: 0.1.0
    values:
      - values/cert-manager-cluster-issuer.yaml

  - name: victoria-metrics-stack-enhancements
    namespace: victoria-metrics-stack
    chart: ./charts/victoria-metrics-stack-enhancements
    version: 0.1.0

  - name: vm
    namespace: victoria-metrics-stack
    chart: victoria-metrics/victoria-metrics-k8s-stack
    version: 0.19.2
    dependencies:
      - chart: nixys/universal-chart
        version: 2.4.0
        alias: grafana_dashboards
    values:
      - values/victoria-metrics-stack.yaml.gotmpl
      - values/grafana-dashboards.yaml.gotmpl

  - name: pgo
    namespace: pgo
    chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
    version: 5.5.0
    values:
      - values/pgo.yaml.gotmpl

  - name: descheduler
    namespace: kube-system
    chart: descheduler/descheduler
    version: 0.29.0
    values:
      - values/descheduler.yaml.gotmpl

  - name: node-problem-detector
    namespace: kube-system
    chart: deliveryhero/node-problem-detector
    version: 2.3.12
    values:
      - values/node-problem-detector.yaml.gotmpl

  - name: minio-operator
    namespace: minio-operator
    chart: minio/operator
    version: 5.0.11
    values:
      - values/minio-operator.yaml.gotmpl

# That's just a tenant's name
#  - name: minio-longhorn-enhancements
#    namespace: longhorn
#    chart: ./charts/minio-longhorn-enhancements
#    version: 0.1.0

#  - name: minio-longhorn
#    namespace: longhorn
#    chart: minio/tenant
#    version: 5.0.11
#    values:
#      - values/minio-longhorn.yaml.gotmpl
