---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-credentials-s3
spec:
  type: kv-v2
  mount: kvv2
  path: longhorn/longhorn-credentials-s3
  destination:
    name: longhorn-credentials-s3
    create: true
  vaultAuthRef: longhorn
