$script = <<-SCRIPT
# I just want the internet!
sed -i 's#nameserver.*#nameserver 8.8.8.8##' /etc/resolv.conf
apt-get update -y
apt-get upgrade -y
apt-get install -y\
  docker.io

usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = 'debian/bookworm64'
  #config.vm.box_version = "12.20230615.1"

  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '50GB'
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provider "libvirt" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true
  #config.vm.synced_folder './image-specs', '/image-specs'

  config.vm.provision "shell", inline: $script
  config.vm.provision 'shell', reboot: true
end
