---
bases:
  - ../lib/base.yaml

repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts
  - name: minio
    url: https://operator.min.io/

releases:
  - name: pacoloco
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: pacoloco
    inherit:
      - template: argocd-app

  - name: invidious
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: invidious
    inherit:
      - template: argocd-app

  - name: redbot
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: redbot
    inherit:
      - template: argocd-app

  - name: netbootxyz
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: netbootxyz
    inherit:
      - template: argocd-app

  - name: home-assistant
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: home-assistant
    inherit:
      - template: argocd-app

  - name: media-storage
    namespace: media
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: media-storage
    values:
      - targetNamespace: media
    inherit:
      - template: argocd-app

  - name: filebrowser
    namespace: media
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: filebrowser
    values:
      - targetNamespace: media
    inherit:
      - template: argocd-app

  - name: metube
    namespace: media
    chart: bjw-s/app-template
    version: 3.3.2
    inherit:
      - template: default
  - name: metube
    values:
      - targetNamespace: media
    inherit:
      - template: argocd-app

  - name: jellyfin
    namespace: media
    chart: oci://tccr.io/truecharts/jellyfin
    version: 20.1.6
    inherit:
      - template: default
  - name: jellyfin
    values:
      - targetNamespace: media
    inherit:
      - template: argocd-app

  - name: minio-core
    chart: minio/tenant
    version: 5.0.11
    inherit:
      - template: default
    dependencies:
      - chart: bjw-s/app-template
        version: 3.3.2
  - name: minio-core
    inherit:
      - template: argocd-app

  - name: minio-private
    chart: minio/tenant
    version: 5.0.11
    inherit:
      - template: default
    dependencies:
      - chart: ./charts/minio-private-enhancements
        version: 0.1.0
  - name: minio-private
    inherit:
      - template: argocd-app
