---
repositories:
  - name: bjw-s
    url: https://bjw-s.github.io/helm-charts
  - name: minio
    url: https://operator.min.io/

releases:
  - name: pacoloco
    namespace: pacoloco
    chart: bjw-s/app-template
    version: 2.6.0
    values:
      - values/pacoloco.yaml.gotmpl

  - name: invidious-enhancements
    namespace: invidious
    chart: ./charts/invidious-enhancements
    version: 0.1.0

  - name: invidious
    namespace: invidious
    chart: bjw-s/app-template
    version: 2.6.0
    values:
      - values/invidious.yaml.gotmpl

  - name: home-assistant-enhancements
    namespace: home-assistant
    chart: ./charts/home-assistant-enhancements
    version: 0.1.0

  - name: home-assistant
    namespace: home-assistant
    chart: bjw-s/app-template
    version: 2.6.0
    values:
      - values/home-assistant.yaml.gotmpl

  - name: minio-operator
    namespace: minio-operator
    chart: minio/operator
    version: 5.0.11
    values:
      - values/minio-operator.yaml.gotmpl

  # That's just a tenant's name
  - name: minio-core-enhancements
    namespace: minio-core
    chart: ./charts/minio-core-enhancements
    version: 0.1.0

  - name: minio-core
    namespace: minio-core
    chart: minio/tenant
    version: 5.0.11
    values:
      - values/minio-core.yaml.gotmpl
