---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redbot
spec:
  type: kv-v2
  mount: kvv2
  path: services/redbot/secrets
  destination:
    name: redbot
    create: true
  vaultAuthRef: redbot
