#!/usr/bin/env bash
# longhorn-scale.sh
#
# Helper for pausing everything that holds a Longhorn PVC open before a
# storage-network (or other disruptive) change, and bringing it back up
# afterwards.
#
# Usage:
#   ./longhorn-scale.sh status   # list PVCs/volumes still attached
#   ./longhorn-scale.sh down     # pause operator-managed DBs + scale plain workloads to 0
#   ./longhorn-scale.sh up       # reverse: unpause DBs + restore saved replica counts
#
# Requires: kubectl, jq

set -euo pipefail

STATE_FILE="${STATE_FILE:-/tmp/longhorn-scale-state.json}"
LONGHORN_NS="${LONGHORN_NS:-longhorn}"
# Comma-separated override if you ever want to restrict to specific classes;
# by default we discover every StorageClass backed by the Longhorn CSI driver,
# so all of longhorn / longhorn-ssd / *-single-replica / *-double-replica /
# longhorn-static etc. are covered without listing them by name.
STORAGE_CLASSES_OVERRIDE="${STORAGE_CLASSES:-}"

log() { echo "[$(date +%H:%M:%S)] $*" >&2; }

longhorn_storage_classes() {
  if [ -n "$STORAGE_CLASSES_OVERRIDE" ]; then
    jq -cn --arg csv "$STORAGE_CLASSES_OVERRIDE" '$csv | split(",")'
  else
    kubectl get storageclass -o json | jq -c '
      [.items[] | select(.provisioner == "driver.longhorn.io") | .metadata.name]'
  fi
}

# ---------------------------------------------------------------------------
# status: list every Longhorn volume that isn't fully detached, with its PVC
# ---------------------------------------------------------------------------
status() {
  echo "Longhorn volumes not currently detached:"
  kubectl get volumes.longhorn.io -n "$LONGHORN_NS" -o json | jq -r '
    .items[]
    | select(.status.state != "detached")
    | [.status.state,
       (.status.kubernetesStatus.namespace // "-"),
       (.status.kubernetesStatus.pvcName // "-"),
       .metadata.name]
    | @tsv
  ' | (echo -e "STATE\tNAMESPACE\tPVC\tVOLUME"; cat) | column -t -s $'\t'
}

# ---------------------------------------------------------------------------
# find plain Deployments/StatefulSets (not owned by an operator CR) that
# mount a PVC backed by any Longhorn storage class, either directly or via
# volumeClaimTemplates
# ---------------------------------------------------------------------------
longhorn_pvc_set() {
  local classes
  classes=$(longhorn_storage_classes)
  kubectl get pvc -A -o json | jq -c --argjson classes "$classes" '
    [.items[]
     | select(.spec.storageClassName as $sc | $classes | index($sc) != null)
     | "\(.metadata.namespace)/\(.metadata.name)"]'
}

find_plain_workloads() {
  local pvcs classes
  pvcs=$(longhorn_pvc_set)
  classes=$(longhorn_storage_classes)

  kubectl get deploy,sts -A -o json | jq -c --argjson pvcs "$pvcs" --argjson classes "$classes" '
    .items[]
    | (.metadata.namespace) as $ns
    | select(
        # skip anything owned by an operator CR (Postgres operators manage
        # their own StatefulSets/Pods; this excludes those automatically)
        ((.metadata.ownerReferences // []) | length) == 0
      )
    | select(
        # direct PVC reference in the pod template — covers Deployments AND
        # StatefulSets that mount a pre-created PVC by claimName (e.g. the
        # app-template/Home Assistant pattern), not just volumeClaimTemplates
        ((.spec.template.spec.volumes // [])
          | map(select(.persistentVolumeClaim != null)
                | "\($ns)/\(.persistentVolumeClaim.claimName)")
          | any(. as $c | $pvcs | index($c) != null))
        or
        # per-replica PVCs generated by a StatefulSet volumeClaimTemplates
        ((.spec.volumeClaimTemplates // [])
          | any(.spec.storageClassName as $sc | $classes | index($sc) != null))
      )
    | {kind, namespace: $ns, name: .metadata.name, replicas: .spec.replicas}
  '
}

# ---------------------------------------------------------------------------
# down: pause operator-managed DBs, scale plain workloads to 0
# ---------------------------------------------------------------------------
down() {
  log "Saving state to $STATE_FILE"
  find_plain_workloads | jq -s '.' > "$STATE_FILE"

  log "Pausing CrunchyData PostgresClusters (spec.shutdown=true)"
  kubectl get postgresclusters.postgres-operator.crunchydata.com -A -o json 2>/dev/null \
    | jq -r '.items[] | "\(.metadata.namespace) \(.metadata.name)"' \
    | while read -r ns name; do
        log "  shutdown: $ns/$name"
        kubectl patch postgrescluster/"$name" -n "$ns" --type merge -p '{"spec":{"shutdown": true}}'
      done || true

  log "Hibernating CloudNativePG clusters (cnpg.io/hibernation=on)"
  kubectl get clusters.postgresql.cnpg.io -A -o json 2>/dev/null \
    | jq -r '.items[] | "\(.metadata.namespace) \(.metadata.name)"' \
    | while read -r ns name; do
        log "  hibernate: $ns/$name"
        kubectl annotate cluster "$name" -n "$ns" --overwrite cnpg.io/hibernation=on
      done || true

  log "Scaling plain Deployments/StatefulSets to 0"
  jq -c '.[]' "$STATE_FILE" | while read -r item; do
    kind=$(jq -r '.kind' <<<"$item")
    ns=$(jq -r '.namespace' <<<"$item")
    name=$(jq -r '.name' <<<"$item")
    log "  scale 0: $kind/$ns/$name"
    kubectl scale "$kind" "$name" -n "$ns" --replicas=0
  done

  log "Waiting for Longhorn volumes to detach..."
  for i in $(seq 1 60); do
    remaining=$(kubectl get volumes.longhorn.io -n "$LONGHORN_NS" -o json \
      | jq '[.items[] | select(.status.state != "detached")] | length')
    if [ "$remaining" -eq 0 ]; then
      log "All volumes detached."
      return 0
    fi
    log "  still attached: $remaining (retry $i/60)"
    sleep 5
  done
  log "WARNING: timed out waiting for full detach — check 'status' before proceeding."
  return 1
}

# ---------------------------------------------------------------------------
# up: reverse everything down() did
# ---------------------------------------------------------------------------
up() {
  if [ ! -f "$STATE_FILE" ]; then
    log "No state file at $STATE_FILE — nothing recorded to restore."
  else
    log "Restoring saved replica counts"
    jq -c '.[]' "$STATE_FILE" | while read -r item; do
      kind=$(jq -r '.kind' <<<"$item")
      ns=$(jq -r '.namespace' <<<"$item")
      name=$(jq -r '.name' <<<"$item")
      replicas=$(jq -r '.replicas' <<<"$item")
      log "  scale $replicas: $kind/$ns/$name"
      kubectl scale "$kind" "$name" -n "$ns" --replicas="$replicas"
    done
  fi

  log "Un-pausing CrunchyData PostgresClusters"
  kubectl get postgresclusters.postgres-operator.crunchydata.com -A -o json 2>/dev/null \
    | jq -r '.items[] | "\(.metadata.namespace) \(.metadata.name)"' \
    | while read -r ns name; do
        log "  resume: $ns/$name"
        kubectl patch postgrescluster/"$name" -n "$ns" --type merge -p '{"spec":{"shutdown": false}}'
      done || true

  log "Un-hibernating CloudNativePG clusters"
  kubectl get clusters.postgresql.cnpg.io -A -o json 2>/dev/null \
    | jq -r '.items[] | "\(.metadata.namespace) \(.metadata.name)"' \
    | while read -r ns name; do
        log "  wake: $ns/$name"
        kubectl annotate cluster "$name" -n "$ns" --overwrite cnpg.io/hibernation=off
      done || true

  log "Done. Run '$0 status' to confirm everything reattached."
}

case "${1:-}" in
  status) status ;;
  down)   down ;;
  up)     up ;;
  *) echo "Usage: $0 {status|down|up}"; exit 1 ;;
esac
