---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: invidious-db
spec:
  postgresVersion: 15
  users:
    - name: invidious
      databases:
        - invidious
      # TODO: These permissions can be probably much more fine-grained
      # We want to keep them quite lax, as the program itself is responsible
      # for creating the initial table layout.
      # This takes the burden off of our shoulders.
      options: "SUPERUSER"
  instances:
    - name: invidious-db
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 20Gi
