---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: invidious-hmac
spec:
  type: kv-v2
  mount: kvv2
  path: services/invidious/hmac
  destination:
    name: invidious-hmac
    create: true
  vaultAuthRef: invidious
