---
# Following instructions from https://www.home-assistant.io/integrations/bluetooth/#additional-details-for-container
# to be used specifically with home-assistant

- name: Install bluez and replace DBus broker
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - bluez
      - dbus-broker
    state: present
  register: bluetooth_installation

- name: Reboot the node if bluetooth setup changed
  become: true
  become_user: root
  when: bluetooth_installation.changed
  ansible.builtin.reboot:
    reboot_timeout: 300
