{
 "title": "Home Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Carbon Dioxide",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "avg(hass_sensor_carbon_dioxide_ppm{entity=\"sensor.wellbeing_air_purifier_eco2\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(hass_sensor_temperature_celsius)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(hass_sensor_humidity_percent)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Carbon Dioxide",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hass_sensor_carbon_dioxide_ppm{entity=\"sensor.wellbeing_air_purifier_eco2\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hass_sensor_temperature_celsius)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hass_sensor_humidity_percent)"
    }
   ]
  },
  {
   "title": "PM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg(hass_sensor_pm10_u0xb5g_per_mu0xb3)",
     "legendFormat": "pm10"
    },
    {
     "expr": "avg(hass_sensor_pm25_u0xb5g_per_mu0xb3)",
     "legendFormat": "pm2.5"
    },
    {
     "expr": "avg(hass_sensor_pm1_u0xb5g_per_mu0xb3)",
     "legendFormat": "pm1"
    }
   ]
  },
  {
   "title": "Volatile Organic Compound Density",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "avg(hass_sensor_unit_ppb)", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}