---
- name: Set timezone
  become: true
  become_user: root
  community.general.timezone:
    name: "{{ vars.timezone }}"
    hwclock: UTC

- name: Set hostname
  become: true
  become_user: root
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set max_watches in sysctl
  become: true
  become_user: root
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: fs.inotify.max_user_watches
      # 5mil
      value: 5000000
      # - name: fs.inotify.max_user_instances
      # - name: fs.inotify.max_queued_events
