---
- name: Set up user
  hosts: all
  become: true
  become_user: root
  vars:
    # Use the bootstrapped user to perform the actions
    ansible_user: ansible_bootstrap
  tags:
    - initial_setup_user
  roles:
    - server_user

- name: Clean up bootstrap user
  hosts: all
  become: true
  become_user: root
  vars:
    # a little hack to allow this playbook to be run at once, without separation
    ansible_become_pass: "{{ user_password | default('ansible_become_pass') }}"
  tags:
    - initial_setup_cleanup
  roles:
    - {role: cleanup_bootstrap_user, when: vars.cleanup_bootstrap_user}
