---
k8s_controlplanes:
  hosts:
    homeserver-five:
    homeserver-six:
    homeserver-seven:

    homeserver-backup-one:
    homeserver-backup-two:
    homeserver-backup-three:
  vars:
    k3s_control_node: true
    node_label:
      - node.longhorn.io/create-default-disk=true

k8s_workers:
  # TODO: an empty node_label list breaks the initialization and flannel
  # for now let's just add a label for each node, falling back to dummylabel
  hosts:
  vars:
    node_label:
      - dezeroku.com/dummy-label=true

k8s_homeserver:
  hosts:
    homeserver-five:
    homeserver-six:
    homeserver-seven:
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_release_version: v1.30.3+k3s1
    k3s_tls_san:
      - homeserver

k8s_homeserver_backup:
  hosts:
    homeserver-backup-one:
    homeserver-backup-two:
    homeserver-backup-three:
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_release_version: v1.30.3+k3s1
    k3s_tls_san:
      - homeserver-backup

k8s_nodes:
  children:
    k8s_homeserver:
    k8s_homeserver_backup:

misc:
  hosts:
    printserver:

rack_rpis:
  hosts:
    homeserver-one:
    homeserver-two:
    homeserver-three:
    homeserver-four:
  vars:
    poe_plus_hat: true
    raspi_os: true

rack_dells:
  hosts:
    homeserver-five:
    homeserver-six:
    homeserver-seven:

all:
  children:
    misc:
    k8s_nodes:
  vars:
    ansible_connection: ssh
    ansible_user: server
    # username to use during the initial provisioning
    ansible_bootstrap_user: ansible_bootstrap
    ssh_pub_key_file: ~/.ssh/id_smartcard_dezeroku.pub
    cleanup_bootstrap_user: true
    upgrade_packages: false
    timezone: Europe/Warsaw
