---
k8s_controlplanes:
  hosts:
    homeserver-one:
      vars:
        k3s_tls_san:
          - homeserver
          - homeserver-one
    homeserver-two:
      vars:
        k3s_tls_san:
          - homeserver
          - homeserver-two
    homeserver-three:
      vars:
        k3s_tls_san:
          - homeserver
          - homeserver-three
  vars:
    k3s_control_node: true
    node_label:
      - node.longhorn.io/create-default-disk=true

k8s_workers:
  hosts:
    homeserver-four:
      poe_plus_hat: true
      raspi_os: true
  vars:
    node_label: []

k8s_nodes:
  children:
    k8s_controlplanes:
    k8s_workers:
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_release_version: v1.27.3+k3s1

misc:
  hosts:
    printserver:

all:
  children:
    misc:
    k8s_nodes:
  vars:
    ansible_connection: ssh
    ansible_user: server
    # Used for the tag initial_setup
    user_name: server
    ssh_pub_key_file: ~/.ssh/id_smartcard_dezeroku.pub
    cleanup_bootstrap_user: true
    upgrade_packages: false
    timezone: Europe/Warsaw
