---
k8s_controlplanes:
  hosts:
    homeserver-five:
    homeserver-six:
    homeserver-seven:
  vars:
    k3s_control_node: true
    node_label:
      - node.longhorn.io/create-default-disk=true

k8s_workers:
  hosts:
    homeserver-one:
      vars:
        node_label:
          - node.longhorn.io/create-default-disk=true
    homeserver-two:
      vars:
        node_label:
          - node.longhorn.io/create-default-disk=true
    homeserver-three:
    homeserver-four:
      vars:
        node_label:
          - node.longhorn.io/create-default-disk=true
  vars:
    node_label: []

k8s_nodes:
  children:
    k8s_controlplanes:
    k8s_workers:
  vars:
    k3s_become: true
    k3s_etcd_datastore: true
    k3s_release_version: v1.30.3+k3s1
    k3s_tls_san:
      - homeserver

misc:
  hosts:
    printserver:

rack_rpis:
  hosts:
    homeserver-one:
    homeserver-two:
    homeserver-three:
    homeserver-four:
  vars:
    poe_plus_hat: true
    raspi_os: true

rack_dells:
  hosts:
    homeserver-five:
    homeserver-six:
    homeserver-seven:

all:
  children:
    misc:
    k8s_nodes:
  vars:
    ansible_connection: ssh
    ansible_user: server
    # username to use during the initial provisioning
    ansible_bootstrap_user: ansible_bootstrap
    ssh_pub_key_file: ~/.ssh/id_smartcard_dezeroku.pub
    cleanup_bootstrap_user: true
    upgrade_packages: false
    timezone: Europe/Warsaw
