---
k8s_controlplanes:
  hosts:
    homeserver-one:
      ansible_connection: ssh
      ansible_user: server
      k3s_etcd_datastore: true
      k3s_control_node: true
      k3s_tls_san:
        - homeserver
        - homeserver-one
      node_label:
        - node.longhorn.io/create-default-disk=true
    homeserver-two:
      ansible_connection: ssh
      ansible_user: server
      k3s_etcd_datastore: true
      k3s_control_node: true
      k3s_tls_san:
        - homeserver
        - homeserver-two
      node_label:
        - node.longhorn.io/create-default-disk=true
    homeserver-three:
      ansible_connection: ssh
      ansible_user: server
      k3s_etcd_datastore: true
      k3s_control_node: true
      k3s_tls_san:
        - homeserver
        - homeserver-three
      node_label:
        - node.longhorn.io/create-default-disk=true
  vars:
    # Used for the tag initial_setup
    user_name: server
    ssh_pub_key_file: ~/.ssh/id_smartcard_dezeroku.pub
    cleanup_bootstrap_user: true

    k3s_become: true
    upgrade_packages: false
    timezone: Europe/Warsaw

misc:
  hosts:
    printserver:
      ansible_connection: ssh
      ansible_user: server
  vars:
    # Used for the tag initial_setup
    user_name: server
    ssh_pub_key_file: ~/.ssh/id_smartcard_dezeroku.pub
    cleanup_bootstrap_user: true

    upgrade_packages: false
    timezone: Europe/Warsaw
