---
- name: Install k3s services dependencies
  hosts: k8s_nodes
  become: true
  become_user: root
  roles:
    - {role: longhorn}

- name: Run k3s preflight tasks
  hosts: k8s_nodes
  become: true
  become_user: root
  tasks:
    - name: Disable swap (RPios)
      when: raspi_os | default("false") | bool
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: dphys-swapfile
        state: stopped
        enabled: false

- name: Set up k3s
  hosts: k8s_nodes
  become: true
  become_user: root
  vars:
    k3s_server:
      disable:
        - traefik
      tls-san:
        - "{{ vars.k3s_tls_san | mandatory }}"
      node-label:
        - "{{ vars.node_label | mandatory }}"
      write-kubeconfig-mode: "0644"
    k3s_agent:
    # TODO: default labels
    # an empty list breaks the initialization and flannel
    # node-label:
    #   - "{{ vars.node_label | mandatory }}"
  roles:
    - role: xanmanning.k3s
