---
- name: Install k3s services dependencies
  hosts: k8s_nodes
  become: true
  become_user: root
  roles:
    - {role: longhorn}

- name: Run k3s preflight tasks
  hosts: k8s_nodes
  become: true
  become_user: root
  tasks:
    - name: Disable swap (RPios)
      when: raspi_os | default("false") | bool
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: dphys-swapfile
        state: stopped
        enabled: false

- name: Set up k3s
  hosts: k8s_homeserver
  become: true
  become_user: root
  vars:
    k3s_server: &k3s_server_settings
      disable:
        - traefik
      tls-san:
        - "{{ vars.k3s_tls_san | mandatory }}"
      node-label:
        - "{{ vars.node_label | mandatory }}"
      write-kubeconfig-mode: "0644"
      #  k3s_agent:
      #    # an empty list breaks the initialization and flannel
      #    node-label:
      #      - "{{ vars.node_label | mandatory }}"
  roles:
    - role: xanmanning.k3s

- name: Set up k3s (backup cluster)
  hosts: k8s_homeserver_backup
  become: true
  become_user: root
  vars:
    k3s_server: *k3s_server_settings
    # k3s_agent:
    #   # an empty list breaks the initialization and flannel
    #   node-label:
    #     - "{{ vars.node_label | mandatory }}"
  roles:
    - role: xanmanning.k3s
