---
- name: Install k3s services dependencies
  hosts: k8s_nodes
  become: true
  become_user: root
  roles:
    - {role: longhorn}

- name: Set up k3s
  hosts: k8s_nodes
  become: true
  become_user: root
  vars:
    k3s_server:
      disable:
        - traefik
      tls-san:
        - "{{ vars.k3s_tls_san | mandatory }}"
      node-label:
        - "{{ vars.node_label | mandatory }}"
      write-kubeconfig-mode: "0644"
    k3s_agent:
      node-label:
        - "{{ vars.node_label | mandatory }}"
  roles:
    - role: xanmanning.k3s
