---
- name: Set up printserver
  hosts: printserver
  become: true
  become_user: root
  tags:
    - printserver
  vars:
    cups_printer_model: "P1102"
    cups_printer_name: "HP_LaserJet_P1102"
  roles:
    - role: cups
