---
- name: Initial user setup
  import_playbook: initial-setup.yml

- name: Base setup
  import_playbook: base-setup.yml

- name: Upgrade packages
  import_playbook: upgrade-packages.yml
  when: vars.upgrade_packages

- name: Install docker-runtime
  hosts: all
  become: true
  become_user: root
  tags:
    - never  # don't run by default
    - docker_runtime
  roles:
    - {role: docker_runtime}

- name: Set up k3s server
  import_playbook: k3s.yml

- name: Set up printserver
  import_playbook: printserver.yml
