---
- name: Obtain user_password from Bitwarden, if it's not explicitly provided
  hosts: all
  tags:
    - always
  gather_facts: false
  pre_tasks:
    # Get password from Bitwarden if neither user_password nor ansible_become_pass is provided
    - name: Obtain user_password from Bitwarden
      # Throttle to one, so the rbw can keep the password in memory
      throttle: 1
      ansible.builtin.command:
        cmd: rbw get homeserver
      check_mode: false
      changed_when: false
      delegate_to: 127.0.0.1
      register: user_password_bitwarden
      when: user_password | default(ansible_become_pass) | default("") | length < 1

    - name: Set user_password from Bitwarden
      when: user_password | default(ansible_become_pass) | default("") | length < 1
      ansible.builtin.set_fact:
        # TODO: This looks like a hot mess, refactor the whole approach later
        user_password: "{{ user_password_bitwarden.stdout }}"
        ansible_become_pass: "{{ user_password_bitwarden.stdout }}"

- name: Initial setup
  import_playbook: initial-setup.yml

- name: Base setup
  import_playbook: base-setup.yml

- name: Upgrade packages
  import_playbook: upgrade-packages.yml
  when: vars.upgrade_packages

- name: Install docker-runtime
  hosts: all
  become: true
  become_user: root
  tags:
    - never  # don't run by default
    - docker_runtime
  roles:
    - {role: docker_runtime}

- name: Set up k3s server
  import_playbook: k3s.yml

- name: Set up printserver
  import_playbook: printserver.yml
