variable "victoria_metrics_alertmanager_pagerduty_token" {
  type = string
}

variable "homeserver_backup_victoria_metrics_alertmanager_pagerduty_token" {
  type = string
}

variable "victoria_metrics_alertmanager_deadmanssnitch_url" {
  type = string
}

variable "users" {
  type = map(object({
    email    = string
    password = string
    groups   = list(string)
  }))
}

variable "domain" {
  type = string
}

variable "oauth2_proxy_cookie_secret" {
  type = string
}

variable "cert_manager_aws_access_key_id" {
  type = string
}

variable "cert_manager_aws_secret_access_key" {
  type = string
}

variable "argocd_credentials_homelab_private_key" {
  type = string
}

variable "minio_root_username" {
  type = string
}

variable "minio_root_password" {
  type = string
}

variable "minio_dezeroku_username" {
  type = string
}

variable "minio_dezeroku_password" {
  type = string
}

variable "minio_private_root_username" {
  type = string
}

variable "minio_private_root_password" {
  type = string
}

variable "minio_private_dezeroku_username" {
  type = string
}

variable "minio_private_dezeroku_password" {
  type = string
}

variable "minio_k8s_backups_root_username" {
  type = string
}

variable "minio_k8s_backups_root_password" {
  type = string
}

variable "minio_k8s_backups_backuper_username" {
  type = string
}

variable "minio_k8s_backups_backuper_password" {
  type = string
}

variable "minio_longhorn_root_username" {
  type = string
}

variable "minio_longhorn_root_password" {
  type = string
}

variable "minio_longhorn_longhorn_username" {
  type = string
}

variable "minio_longhorn_longhorn_password" {
  type = string
}

variable "minio_longhorn_endpoint" {
  type = string
}

variable "tgtg_username" {
  type = string
}

variable "tgtg_ses_from" {
  type = string
}

variable "tgtg_ses_to" {
  type = string
}

variable "ses_access_key_id" {
  type = string
}

variable "ses_access_key_secret" {
  type = string
}

variable "home_assistant_prometheus_token" {
  type = string
}

variable "invidious_hmac_key" {
  type = string
}

#variable "redbot_owner" {
#  type = string
#}

variable "redbot_main_token" {
  type = string
}

variable "redbot_premiers_token" {
  type = string
}

variable "homepage_jellyfin_apikey" {
  # TODO: this value is currently generated by hand via Jellyfin UI
  # Automate the process
  type = string
}

variable "paperless_secret_key" {
  type = string
}

variable "paperless_admin_username" {
  type = string
}

variable "paperless_admin_password" {
  type = string
}

variable "paperless_admin_email" {
  type = string
}

variable "paperless_redis_password" {
  type = string
}

variable "paperless_ses_incoming_recipients" {
  type = list(string)
}

variable "paperless_ses_senders_regex" {
  type = string
}

variable "wikijs_oidc_auth_id" {
  type = string
}

variable "ses_smtp_username" {
  type = string
}

variable "ses_smtp_password" {
  type = string
}

variable "ses_smtp_host" {
  type = string
}

variable "minecraft_rcon_password" {
  type = string
}

variable "backup_cluster_kubernetes_host" {
  type = string
}

variable "backup_cluster_kubernetes_ca_cert" {
  type = string
}

variable "backup_cluster_token_reviewer_jwt" {
  type = string
}

variable "kopia_control_user_username" {
  type = string
}

variable "kopia_control_user_password" {
  type = string
}

variable "kopia_server_user_username" {
  type = string
}

variable "kopia_server_user_password" {
  type = string
}

variable "kopia_repository_password" {
  type = string
}

variable "kopia_target_users" {
  # Use a list, as usernames can contain @ character
  type = list(object({
    username = string
    password = string
  }))
}

variable "kopia_pushover_app_token" {
  type = string
}

variable "kopia_pushover_user_key" {
  type = string
}

variable "mailrise_pushover_general_user_key" {
  type = string
}

variable "mailrise_pushover_general_api_key" {
  type = string
}

variable "mosquitto_username" {
  type = string
}

variable "mosquitto_password" {
  type = string
}

variable "mosquitto_passwordfile" {
  type = string
}

variable "ryot_admin_token" {
  type = string
}
