name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 37.368.6
